curl: fix `git clone` targeting Bitbucket
A regression introduced into cURL v7.87.0 causes clones from Bitbucket
repositories that use the Secure Channel backend to fail in this fashion:

	$ git -c http.sslbackend=schannel clone https://jurko@bitbucket.org/jurko/testinggit.git
	Cloning into 'testinggit'...
	remote: Enumerating objects: 3, done.
	remote: Counting objects: 100% (3/3), done.
	remote: Compressing objects: 100% (2/2), done.
	remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
	error: RPC failed; curl 56 Failure when receiving data from the peer
	Unpacking objects: 100% (3/3), 590 bytes | 98.00 KiB/s, done.

The fix for this was already applied in cURL's main-line branch. Let's
backport it.

This fixes https://github.com/git-for-windows/git/issues/4194

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>